apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura-svc
spec:
  type: NodePort
  selector:
    app: cronversao-temperatura-app
  ports:
  - port: 30000
    targetPort: 8080
    nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronversao-temperatura-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cronversao-temperatura-app
  template:
    metadata:
      labels:
        app: cronversao-temperatura-app
    spec:
      containers:
      - name: cronversao-temperatura-app
        image: affigueiredo/conversao-temperatura:latest
        ports:
        - containerPort: 8080
